name: favorite_place_app
description: A Flutter app to store your favorite places using camera, location, and maps.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  image_picker: ^1.1.0
  path_provider: ^2.1.2
  google_maps_flutter: ^2.6.1
  geolocator: ^14.0.2
  sqflite: ^2.3.2
  path: ^1.9.0
  provider: ^6.1.2
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/